/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermercado;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import supermercado.controller.ProdutoController;
import supermercado.helper.EntityManagerHelper;
import supermercado.model.Funcionario;
import supermercado.model.ItemVenda;
import supermercado.model.Produto;
import supermercado.model.Venda;
import supermercado.util.MathUtil;

/**
 *
 * @author KillerWorkstation
 */
public class Caixa extends javax.swing.JDialog {
    private ArrayList<ItemVenda> listaVenda = new ArrayList<>();
    private DefaultListModel<String> model = new DefaultListModel<>();
    private Venda venda;
    private int caixa;

    public Caixa(int caixa) {
        this.caixa = caixa;
        initComponents();
        this.setTitle("Supermercado - Caixa " + caixa);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        lblFuncionario.setText(Funcionario.getFuncionario().getNome());
        lblCaixa.setText("Caixa " + caixa);
        initNewVenda();
        jList1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigoProduto = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        lblFuncionario = new javax.swing.JLabel();
        lblCaixa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtCodigoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoProdutoKeyPressed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        lblFuncionario.setText("Funcionario");

        lblCaixa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblCaixa.setText("Caixa");

        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Código do Produto");

        jButton1.setText("Finalizar Venda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Total");

        txtTotal.setEditable(false);
        txtTotal.setText("R$ 0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCaixa)
                        .addComponent(lblFuncionario)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAdicionar))
                        .addComponent(jLabel1)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCaixa)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        addProduto();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private boolean addProduto() {
        Double quantidade;
        Produto produto;
        ItemVenda itemVenda;
        if (txtCodigoProduto.getText().isEmpty()) {
            return true;
        }
        produto = new ProdutoController(EntityManagerHelper.entityManagerFactory()).bySimpleNaturalId(txtCodigoProduto.getText().trim());
        if (produto == null) {
            JOptionPane.showMessageDialog(rootPane, "Produto não encontrado");
            return true;
        }
        String retorno = JOptionPane.showInputDialog(rootPane, "Insira a quantidade em ("+produto.getUnidade().toString()+")", produto.getDescricao(), JOptionPane.PLAIN_MESSAGE);
        if(retorno == null || retorno.isEmpty()) {
            return true;
        }
        quantidade = Double.valueOf(retorno.replace(',', '.'));
        if (quantidade == null) {
            return true;
        }
        txtCodigoProduto.setText("");
        itemVenda = new ItemVenda();
        itemVenda.setValor(produto.getValorUnitario().multiply(new BigDecimal(quantidade)));
        itemVenda.setQuantidade(quantidade);
        itemVenda.setProduto(produto);
        listaVenda.add(itemVenda);
        model.addElement(itemVenda.toString());
        atualizarTotal();
        return false;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FinalizarVenda fv = new FinalizarVenda(venda);
        fv.setModal(true);
        if(fv.showDialog()){
            JOptionPane.showMessageDialog(rootPane, "Venda concluída");
            initNewVenda();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCodigoProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProdutoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addProduto();
        }
    }//GEN-LAST:event_txtCodigoProdutoKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCaixa;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void atualizarTotal() {
        BigDecimal total = new BigDecimal(0);
        for (ItemVenda itemVenda : listaVenda) {
            total = total.add(itemVenda.getValor());
        }
        venda.setValor(total);
        txtTotal.setText(MathUtil.Currency.format(total));
    }

    private void initNewVenda() {
        listaVenda.clear();
        venda = new Venda();
        venda.setCaixa(caixa);
        venda.setItensVenda(listaVenda);
        model.clear();
        txtTotal.setText("");
    }
}
