/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermercado;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.util.Date;
import javax.swing.JOptionPane;
import supermercado.controller.VendaController;
import supermercado.helper.EntityManagerHelper;
import supermercado.model.Funcionario;
import supermercado.model.Venda;
import supermercado.util.EnumUtil.Pagamento;
import supermercado.util.MathUtil;

/**
 *
 * @author KillerWorkstation
 */
public class FinalizarVenda extends javax.swing.JDialog {

    private Venda venda;
    private boolean concluida = false;

    public FinalizarVenda(Venda venda) {
        this.venda = venda;
        initComponents();
        this.setTitle("Finalizar Venda");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        txtValorTotal.setText(MathUtil.Currency.format(venda.getValor()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbFormaPagamento = new javax.swing.JComboBox<>();
        btnFinalizar = new javax.swing.JButton();
        txtValorTotal = new javax.swing.JTextField();
        txtValorPago = new javax.swing.JTextField();
        txtTroco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão"}));
        cbFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFormaPagamentoActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        txtValorTotal.setEditable(false);

        txtValorPago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorPagoFocusLost(evt);
            }
        });

        jLabel1.setText("Total");

        jLabel2.setText("Troco");

        jLabel3.setText("Valor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addGap(0, 129, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbFormaPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtValorTotal)
                            .addComponent(txtTroco)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtValorPago))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFormaPagamentoActionPerformed
        txtTroco.setText("");
        txtValorPago.setText("");
        if (cbFormaPagamento.getSelectedIndex() == Pagamento.CARTAO.ordinal()) {
            venda.setPagamento(Pagamento.CARTAO);
            txtValorPago.setEditable(false);
            txtTroco.setEditable(false);
        } else {
            venda.setPagamento(Pagamento.DINHEIRO);
            txtValorPago.setEditable(true);
            txtTroco.setEditable(true);
        }
    }//GEN-LAST:event_cbFormaPagamentoActionPerformed

    private void txtValorPagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorPagoFocusLost
        if (txtValorPago.getText().trim().equals("")) {
            return;
        }
        BigDecimal valorPago;
        try {
            valorPago = new BigDecimal(txtValorPago.getText().replace(',', '.'));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Valor inválido");
            txtValorPago.requestFocus();
            return;
        }
        if (valorPago.compareTo(venda.getValor()) < 0) {
            JOptionPane.showMessageDialog(null, "Valor menor que o total");
            txtValorPago.requestFocus();
            return;
        }
        venda.setTroco(valorPago.subtract(venda.getValor()));
        txtTroco.setText(MathUtil.Currency.format(venda.getTroco()));
    }//GEN-LAST:event_txtValorPagoFocusLost

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        if(venda.getPagamento().equals(Pagamento.DINHEIRO) && txtValorPago.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Informe o valor pago");
            return;
        }
        try {
            concluida = true;
            venda.setData(new Date());
            venda.setFuncionario(Funcionario.getFuncionario());
            VendaController vjc = new VendaController(EntityManagerHelper.entityManagerFactory());
            vjc.create(venda);
        } catch (Exception e) {
            concluida = false;
            JOptionPane.showMessageDialog(rootPane, e.getLocalizedMessage());
        }
        setVisible(false);
        dispose();

    }//GEN-LAST:event_btnFinalizarActionPerformed

    public Boolean showDialog() {
        setVisible(true);
        return concluida;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JComboBox<String> cbFormaPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtValorPago;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
