/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermercado;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import supermercado.controller.VendaController;
import supermercado.helper.EntityManagerHelper;
import supermercado.model.Venda;

/**
 *
 * @author KillerWorkstation
 */
public class RelatorioVendas extends javax.swing.JDialog {
    private int caixa = 1;
    private final DateFormat format = new SimpleDateFormat("dd/MM/yyyy", Locale.getDefault());
    private DefaultListModel<String> defaultListModel;
    /**
     * Creates new form RelatorioVendas
     */
    public RelatorioVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Relatório de Vendas");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        List<Venda> vendas = new VendaController(EntityManagerHelper.entityManagerFactory()).findVendaEntities();
        defaultListModel = new DefaultListModel<>();
        listRelatorio.setModel(defaultListModel);
        txtData.setText(format.format(new Date()));
        
        for (Venda venda : vendas) {
            defaultListModel.addElement(venda.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listRelatorio = new javax.swing.JList<>();
        cbCaixas = new javax.swing.JComboBox<>();
        txtData = new javax.swing.JTextField();
        btnGerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listRelatorio.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listRelatorio);

        cbCaixas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caixa 1", "Caixa 2", "Caixa 3" }));
        cbCaixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCaixasActionPerformed(evt);
            }
        });

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbCaixas, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGerar)
                        .addGap(0, 363, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCaixas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        Date date;
        try {
            date = format.parse(txtData.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getLocalizedMessage());
            return;
        }
        List<Venda> vendas = new VendaController(EntityManagerHelper.entityManagerFactory()).findVendasByDateAndCaixa(date, caixa);
        if(vendas.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Não existem vendas.");
            defaultListModel.clear();
            return;
        }
        defaultListModel.clear();
        for (Venda venda : vendas) {
            defaultListModel.addElement(venda.toString());
        }
        
    }//GEN-LAST:event_btnGerarActionPerformed

    private void cbCaixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCaixasActionPerformed
        this.caixa = cbCaixas.getSelectedIndex() + 1;
    }//GEN-LAST:event_cbCaixasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JComboBox<String> cbCaixas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listRelatorio;
    private javax.swing.JTextField txtData;
    // End of variables declaration//GEN-END:variables
}
