/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermercado;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import supermercado.controller.FuncionarioController;
import supermercado.controller.ItemEstoqueController;
import supermercado.helper.EntityManagerHelper;
import supermercado.model.Funcionario;
import supermercado.model.ItemEstoque;
import supermercado.model.Produto;
import supermercado.util.EnumUtil;

/**
 *
 * @author KillerWorkstation
 */
public class Supermercado extends javax.swing.JFrame {

    public Supermercado() {
        initComponents();
        this.setTitle("Supermercado");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        File f = new File("populated");
        if (!f.exists()) {
            try {
                f.createNewFile();
                populaDB();
            } catch (IOException ex) {
            }

        }
        jPanelGerente.setVisible(false);
        jPanelFuncionario.setVisible(false);
        //populaDB();
        populaCBFuncionario();
    }
    
    private void populaCBFuncionario() {
        FuncionarioController fjc = new FuncionarioController(EntityManagerHelper.entityManagerFactory());
        List<Funcionario> funcionarios = fjc.buscarFuncionarios();
        funcionarios.add(0, null);
        cbFuncionarios.setModel(new DefaultComboBoxModel(funcionarios.toArray()));
    }

    private void populaDB() {
        Funcionario f1 = new Funcionario("Funcionario 1", EnumUtil.Cargo.CAIXA, "func1", "admin");
        Funcionario f2 = new Funcionario("Funcionario 2", EnumUtil.Cargo.CAIXA, "func2", "admin");
        Funcionario f3 = new Funcionario("Funcionario 3", EnumUtil.Cargo.CAIXA, "func3", "admin");
        Funcionario f4 = new Funcionario("Funcionario 4", EnumUtil.Cargo.CAIXA, "func4", "admin");
        Funcionario f5 = new Funcionario("Funcionario 5", EnumUtil.Cargo.CAIXA, "func5", "admin");
        Funcionario f6 = new Funcionario("Gerente", EnumUtil.Cargo.GERENTE, "gerente", "admin");

        Produto p1 = new Produto("11", "Arroz 1", EnumUtil.Unidade.UNIDADE, new BigDecimal(10));
        Produto p2 = new Produto("22", "Arroz 2", EnumUtil.Unidade.UNIDADE, new BigDecimal(9.50));
        Produto p3 = new Produto("33", "Arroz 3", EnumUtil.Unidade.UNIDADE, new BigDecimal(12));
        Produto p4 = new Produto("44", "Arroz 4", EnumUtil.Unidade.UNIDADE, new BigDecimal(14.25));
        Produto p5 = new Produto("55", "Tomate", EnumUtil.Unidade.QUILO, new BigDecimal(1.95));

        ItemEstoque ie = new ItemEstoque(p1, 100.0);
        ItemEstoque ie2 = new ItemEstoque(p2, 100.0);
        ItemEstoque ie3 = new ItemEstoque(p3, 100.0);
        ItemEstoque ie4 = new ItemEstoque(p4, 100.0);
        ItemEstoque ie5 = new ItemEstoque(p5, 100.0);

        FuncionarioController fjc = new FuncionarioController(EntityManagerHelper.entityManagerFactory());
        fjc.criar(f1, f2, f3, f4, f5, f6);

        ItemEstoqueController iejc = new ItemEstoqueController(EntityManagerHelper.entityManagerFactory());
        iejc.create(ie, ie2, ie3, ie4, ie5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbFuncionarios = new javax.swing.JComboBox<>();
        jPanelGerente = new javax.swing.JPanel();
        btnRelatorioVendas = new javax.swing.JButton();
        btnRelatorioEstoque = new javax.swing.JButton();
        btnCadastroProduto = new javax.swing.JButton();
        jPanelFuncionario = new javax.swing.JPanel();
        btnCaixa2 = new javax.swing.JButton();
        btnCaixa3 = new javax.swing.JButton();
        btnCaixa1 = new javax.swing.JButton();
        jPanelCliente = new javax.swing.JPanel();
        btnBuscarProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbFuncionarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFuncionariosActionPerformed(evt);
            }
        });

        btnRelatorioVendas.setText("Relatório Vendas");
        btnRelatorioVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioVendasActionPerformed(evt);
            }
        });

        btnRelatorioEstoque.setText("Relatório Estoque");
        btnRelatorioEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioEstoqueActionPerformed(evt);
            }
        });

        btnCadastroProduto.setText("Cadastrar Produto");
        btnCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGerenteLayout = new javax.swing.GroupLayout(jPanelGerente);
        jPanelGerente.setLayout(jPanelGerenteLayout);
        jPanelGerenteLayout.setHorizontalGroup(
            jPanelGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRelatorioVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRelatorioEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastroProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGerenteLayout.setVerticalGroup(
            jPanelGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRelatorioVendas)
                    .addComponent(btnRelatorioEstoque)
                    .addComponent(btnCadastroProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCaixa2.setText("Caixa 2");
        btnCaixa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa2ActionPerformed(evt);
            }
        });

        btnCaixa3.setText("Caixa 3");
        btnCaixa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa3ActionPerformed(evt);
            }
        });

        btnCaixa1.setText("Caixa 1");
        btnCaixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFuncionarioLayout = new javax.swing.GroupLayout(jPanelFuncionario);
        jPanelFuncionario.setLayout(jPanelFuncionarioLayout);
        jPanelFuncionarioLayout.setHorizontalGroup(
            jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCaixa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCaixa2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCaixa3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFuncionarioLayout.setVerticalGroup(
            jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaixa1)
                    .addComponent(btnCaixa2)
                    .addComponent(btnCaixa3))
                .addContainerGap())
        );

        btnBuscarProduto.setText("Buscar Produto");
        btnBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscarProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelatorioVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioVendasActionPerformed
        new RelatorioVendas(this, true).setVisible(true);
    }//GEN-LAST:event_btnRelatorioVendasActionPerformed

    private void btnRelatorioEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioEstoqueActionPerformed
        new RelatorioEstoque(this, true).setVisible(true);
    }//GEN-LAST:event_btnRelatorioEstoqueActionPerformed

    private void btnCaixa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa2ActionPerformed
        new Caixa(2).setVisible(true);
    }//GEN-LAST:event_btnCaixa2ActionPerformed

    private void btnCaixa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa3ActionPerformed
        new Caixa(3).setVisible(true);
    }//GEN-LAST:event_btnCaixa3ActionPerformed

    private void btnCaixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa1ActionPerformed
        new Caixa(1).setVisible(true);
    }//GEN-LAST:event_btnCaixa1ActionPerformed

    private void cbFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFuncionariosActionPerformed
        Funcionario f1 = (Funcionario) cbFuncionarios.getSelectedItem();
        if (f1 == null) {
            jPanelGerente.setVisible(false);
            jPanelFuncionario.setVisible(false);
            jPanelCliente.setVisible(true);
        } else {
            Login login = new Login(f1);
            login.setModal(true);
            
            if (login.showDialog()) {
                JOptionPane.showMessageDialog(rootPane, "Bem vindo : " + Funcionario.getFuncionario().getNome());
            } else {
                cbFuncionarios.setSelectedIndex(0);
                return;
            }
            
            if (f1.getCargo() == EnumUtil.Cargo.CAIXA) {
                jPanelGerente.setVisible(false);
                jPanelFuncionario.setVisible(true);
                jPanelCliente.setVisible(false);
            } else {
                jPanelGerente.setVisible(true);
                jPanelFuncionario.setVisible(false);
                jPanelCliente.setVisible(false);
            }
        }
    }//GEN-LAST:event_cbFuncionariosActionPerformed

    private void btnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdutoActionPerformed
        new Busca(this, true).setVisible(true);
    }//GEN-LAST:event_btnBuscarProdutoActionPerformed

    private void btnCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroProdutoActionPerformed
        Cadastro dialog = new Cadastro(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnCadastroProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supermercado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnCadastroProduto;
    private javax.swing.JButton btnCaixa1;
    private javax.swing.JButton btnCaixa2;
    private javax.swing.JButton btnCaixa3;
    private javax.swing.JButton btnRelatorioEstoque;
    private javax.swing.JButton btnRelatorioVendas;
    private javax.swing.JComboBox<String> cbFuncionarios;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelFuncionario;
    private javax.swing.JPanel jPanelGerente;
    // End of variables declaration//GEN-END:variables

}
